### ISSUE TITLE
spawn EACCES Error at all the Times

### ISSUE THREAD

**Issue by Dygerati** [AtomLinter/linter-jshint#133]
So, when I startup Atom, open a file, save a file, or do much of anything, I get the much feared red popup that reads as follows:

**spawn EACCCES**
```Error: spawn EACCES
  at exports._errnoException (util.js:734:11)
  at ChildProcess.spawn (child_process.js:1145:11)
  at Object.exports.spawn (child_process.js:977:9)
  at /Users/jthie1/.atom/packages/linter-jshint/node_modules/atom-linter/lib/helpers.coffee:15:38
  at Object.module.exports.Helpers.exec (/Users/jthie1/.atom/packages/linter-jshint/node_modules/atom-linter/lib/helpers.coffee:14:16)
  at Object.provider.lint (/Users/jthie1/.atom/packages/linter-jshint/lib/main.coffee:24:24)
  at /Users/jthie1/.atom/packages/linter/lib/editor-linter.coffee:69:26
  at currentLinter (/Users/jthie1/.atom/packages/linter/lib/editor-linter.coffee:68:20)
  at /Users/jthie1/.atom/packages/linter/lib/editor-linter.coffee:82:23
  at Set.forEach (native)
  at EditorLinter.triggerLinters (/Users/jthie1/.atom/packages/linter/lib/editor-linter.coffee:64:26)
  at /Users/jthie1/.atom/packages/linter/lib/editor-linter.coffee:57:27```


Any thoughts?

EDIT - Forgot to mention, here are relevant versions:
Atom: 1.0.2
Linter: 1.2.3
Linter-jshint: 1.0.5

**Comment by jamsyoung** [comment]
I have this same problem.  It has made the JSHint linter unusable.

Atom: 1.0.2
Linter: 1.2.4
Linter-jshint: 1.0.5

**Comment by Dygerati** [comment]
So, I had manually entered the path to my /bin directory into the plugin even though it was in the default directory. After removing my entry in the settings it seems to work...?

Still seems to be a bug, although perhaps only in these unusual conditions...

**Comment by steelbrain** [comment]
Be advised that `jshintExecutablePath` config was renamed to `executablePath`  recently.

**Comment by jamsyoung** [comment]
Confirmed that if I set a custom path, I get this error, and if I do not set a custom path and "use bundled" I do not get this error.

**Comment by steelbrain** [comment]
Fixed in the latest release.
