### ISSUE TITLE
Failed to activate the linter-jshint package

### ISSUE THREAD

**Issue by yoojung** [AtomLinter/linter-jshint#169]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.15
**System**: Unknown Windows Version
**Thrown From**: [linter-jshint](https://github.com/AtomLinter/linter-jshint) package, v1.2.0

### Stack Trace

Failed to activate the linter-jshint package

```
At Cannot find module 'atom-linter'

Error: Cannot find module 'atom-linter'
    at Module._resolveFilename (module.js:334:15)
    at Function.Module._resolveFilename (C:\Users\유정\AppData\Local\atom\app-1.0.15\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:284:25)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.module.exports.provideLinter (C:\Users\유정\.atom\packages\linter-jshint\lib\main.coffee:40:15)
    at Package.module.exports.Package.activateServices (C:\Users\유정\AppData\Local\atom\app-1.0.15\resources\app.asar\src\package.js:416:69)
    at Package.module.exports.Package.activateNow (C:\Users\유정\AppData\Local\atom\app-1.0.15\resources\app.asar\src\package.js:248:16)
    at C:\Users\유정\AppData\Local\atom\app-1.0.15\resources\app.asar\src\package.js:226:30
    at Package.module.exports.Package.measure (C:\Users\유정\AppData\Local\atom\app-1.0.15\resources\app.asar\src\package.js:169:15)
```

### Commands

```
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
atom-runner, v2.4.3
emmet, v2.3.12
highlight-selected, v0.10.1
linter, v1.5.1
linter-jshint, v1.2.0

# Dev
No dev packages
```

**Comment by steelbrain** [comment]
do this
```
cd ~/.atom/packages/linter-jshint
apm install
```

**Comment by festinalente** [comment]
I'm getting the same error message, but for a different reason it appears:

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.187.0
**System**: linux 3.13.0-71-generic
**Thrown From**: [linter-jshint](https://github.com/AtomLinter/linter-jshint) package, v1.2.1

### Stack Trace

Failed to activate the linter-jshint package

```
At /home/tomas/.atom/packages/linter-jshint/node_modules/atom-linter/lib/helpers.js:79
        const newError = new Error(`Failed to spawn command '${ command }'. Ma
                                   ^
Unexpected token ILLEGAL

/home/tomas/.atom/packages/linter-jshint/node_modules/atom-linter/lib/helpers.js:79
        const newError = new Error(`Failed to spawn command '${ command }'. Ma
                                   ^
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:75:16)
    at Module._compile (module.js:458:25)
    at Object.loadFile [as .js] (/usr/share/atom/resources/app/src/babel.js:162:21)
    at Module.load (module.js:370:32)
    at Function.Module._load (module.js:325:12)
    at Module.require (module.js:380:17)
    at require (module.js:399:17)
    at Object.module.exports.provideLinter (/home/tomas/.atom/packages/linter-jshint/lib/main.coffee:61:17)
    at Package.module.exports.Package.activateServices (/usr/share/atom/resources/app/src/package.js:355:117)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app/src/package.js:243:16)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "jshint",
      "atom-jshint"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-jade, v0.3.0
linter-jshint, v1.2.1

# Dev
No dev packages
```

**Comment by Arcanemagus** [comment]
@festinalente can you file a new issue with that information?

**Comment by Arcanemagus** [comment]
Actually, as @steelbrain just pointed out in chat your Atom is _very_ out of date, updating to the current version should fix this for you.

**Comment by festinalente** [comment]
@Arcanemagus the out of date Atom was the issue. Thanks you.

**Comment by vaer-k** [comment]
I'm up to date. 

1. Launch atom from terminal.
2. Witness error report.

**Atom Version**: 1.4.3
**System**: elementary OS
**Thrown From**: [linter-jshint](https://github.com/AtomLinter/linter-jshint) package, v1.3.0


### Stack Trace

Failed to activate the linter-jshint package

```
At Cannot find module 'consistent-path'

Error: Cannot find module 'consistent-path'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/odin/.atom/packages/linter-jshint/node_modules/atom-linter/lib/helpers.js:33:23)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.module.exports.provideLinter (/home/odin/.atom/packages/linter-jshint/lib/main.coffee:76:17)
    at Package.module.exports.Package.activateServices (/usr/share/atom/resources/app.asar/src/package.js:349:69)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:186:16)
    at /usr/share/atom/resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
    at /usr/share/atom/resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:524:21)
    at /usr/share/atom/resources/app.asar/src/package-manager.js:505:29
    at Config.module.exports.Config.transactAsync (/usr/share/atom/resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/usr/share/atom/resources/app.asar/src/package-manager.js:500:19)
    at PackageManager.module.exports.PackageManager.activate (/usr/share/atom/resources/app.asar/src/package-manager.js:483:46)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (/usr/share/atom/resources/app.asar/src/atom-environment.js:688:21)
    at module.exports (/usr/share/atom/resources/app.asar/src/initialize-application-window.js:28:10)
    at setupWindow (file:///usr/share/atom/resources/app.asar/static/index.js:86:5)
    at window.onload (file:///usr/share/atom/resources/app.asar/static/index.js:41:9)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "vim-mode"
    ],
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  },
  "linter-jshint": {}
}
```

### Installed Packages

```coffee
# User
atom-material-syntax, v0.3.2
atom-material-ui, v0.8.1
atom-ternjs, v0.13.2
language-matlab, v0.2.0
linter, v1.11.3
linter-jshint, v1.3.0
linter-pylint, v1.2.0
minimap, v4.19.0

# Dev
No dev packages
```

**Comment by steelbrain** [comment]
@vaer-k Here's the workaround
```
cd ~/.atom/packages/linter-jshint
npm install consistent-path@latest
```

**Comment by vaer-k** [comment]
@steelbrain Thanks very much.

**Comment by Arcanemagus** [comment]
`npm install` or `apm rebuild`(maybe...) Would have also done the trick as errors like this are all due to `apm` not installing all dependencies of a package for some reason.

**Comment by prajwal-mendon** [comment]
im having a problem installing linter-jshint 
in log it says
error Unexpected end of JSON input while parsing near '...GzSWJafJv8XkRm6ax8e8j'

**Comment by prajwal-mendon** [comment]
145 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...GzSWJafJv8XkRm6ax8e8j'
145 verbose stack     at JSON.parse (<anonymous>)
145 verbose stack     at parseJson (C:\Users\prajwal mendon\Downloads\Atom x64\resources\app\apm\node_modules\npm\node_modules\json-parse-better-errors\index.js:7:17)
145 verbose stack     at consumeBody.call.then.buffer (C:\Users\prajwal mendon\Downloads\Atom x64\resources\app\apm\node_modules\npm\node_modules\node-fetch-npm\src\body.js:96:50)
145 verbose stack     at process._tickCallback (internal/process/next_tick.js:68:7)
146 verbose cwd C:\Users\PRAJWA~1\AppData\Local\Temp\apm-install-dir-1191014-4224-1o5imte.a1sm
147 verbose Windows_NT 6.3.9600
148 verbose argv "C:\\Users\\prajwal mendon\\Downloads\\Atom x64\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\prajwal mendon\\Downloads\\Atom x64\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\prajwal mendon\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\prajwal mendon\\.atom\\.apmrc" "install" "https://www.atom.io/api/packages/linter-jshint/versions/3.1.17/tarball" "--target=4.2.7" "--disturl=https://atom.io/download/electron" "--arch=x64" "--global-style"
149 verbose node v10.2.1
150 verbose npm  v6.2.0
151 error Unexpected end of JSON input while parsing near '...GzSWJafJv8XkRm6ax8e8j'
152 verbose exit [ 1, true ]

**Comment by prajwal-mendon** [comment]
please help
