### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by annarbt** [AtomLinter/linter-jshint#178]
```
Error: module.js:336 throw err; ^ Error: Cannot find module '/home/anna/.atom/packages/linter-jshint/node_modules/jshint/bin' at Function.Module._resolveFilename (module.js:334:15) at Function.Module._load (module.js:284:25) at Function.Module.runMain (module.js:469:10) at startup (node.js:125:18) at node.js:960:3
Error: module.js:336
    throw err;
          ^
Error: Cannot find module '/home/anna/.atom/packages/linter-jshint/node_modules/jshint/bin'
    at Function.Module._resolveFilename (module.js:334:15)
    at Function.Module._load (module.js:284:25)
    at Function.Module.runMain (module.js:469:10)
    at startup (node.js:125:18)
    at node.js:960:3
    at exit (/home/anna/.atom/packages/linter-htmlhint/node_modules/atom-linter/lib/helpers.coffee:33:24)
    at triggerExitCallback (/usr/share/atom/resources/app.asar/src/buffered-process.js:213:47)
    at ChildProcess.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:235:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

I tried reinstalling it using apm but this still comes up.
The path to /home/anna/.atom/packages/linter-jshint/node_modules/jshint/bin seems fine

**Comment by Arcanemagus** [comment]
If you have node.js installed on your computer can you try `npm install` in the package directory?

**Comment by annarbt** [comment]
That worked thanks!
