### ISSUE TITLE
Error: Invalid TextEditor provided Ubuntu x64 1.3.1

### ISSUE THREAD

**Issue by ArekSredzki** [AtomLinter/linter-jshint#205]
Today I started receiving the following error whenever I open a new file or modify it in any way.

```
Error: Invalid TextEditor provided
    at _validateEditor (/home/asredzki/.atom/packages/linter-jshint/node_modules/atom-linter/lib/helpers.js:143:11)
    at Object.rangeFromLineNumber (/home/asredzki/.atom/packages/linter-jshint/node_modules/atom-linter/lib/helpers.js:164:3)
    at /home/asredzki/.atom/packages/linter-jshint/lib/main.coffee:88:31
    at Array.map (native)
    at /home/asredzki/.atom/packages/linter-jshint/lib/main.coffee:77:25
    at process._tickCallback (node.js:368:9)
```

**Comment by steelbrain** [comment]
This has been fixed by https://github.com/AtomLinter/atom-linter/pull/106

As a workaround until that is published, you can upgrade your Atom to 1.4.0+
