### ISSUE TITLE
Error: Invalid TextEditor provided

### ISSUE THREAD

**Issue by lorenzos** [AtomLinter/linter-jshint#206]
This error is thrown every time JS Hint check any JS source in Atom 1.2.4.
I'm using `linter-jshint` 1.3.1 and `linter` 1.11.3.

```
Error: Invalid TextEditor provided
    at _validateEditor (/home/lorenzo/.atom/packages/linter-jshint/node_modules/atom-linter/lib/helpers.js:143:11)
    at Object.rangeFromLineNumber (/home/lorenzo/.atom/packages/linter-jshint/node_modules/atom-linter/lib/helpers.js:164:3)
    at /home/lorenzo/.atom/packages/linter-jshint/lib/main.coffee:88:31
    at Array.map (native)
    at /home/lorenzo/.atom/packages/linter-jshint/lib/main.coffee:77:25
    at process._tickCallback (node.js:368:9)
```

**Comment by lorenzos** [comment]
Sorry, didn't saw #205, I'll try to upgrade Atom.

**Comment by steelbrain** [comment]
Closing as duplicate
