### ISSUE TITLE
Circular structure error

### ISSUE THREAD

**Issue by egens** [AtomLinter/linter-jshint#218]
This code with circular structure error leads to atom error.
```js
function appear() {
    if (op < 1) {
        op += 0.1;
        tipobj.style.opacity = op;
        tipobj.style.filter = 'alpha(opacity=' + op * 100 + ')';
        t = setTimeout('appear()', 5);
    }
}
```

```
Error: /home/egens/.atom/packages/linter-jshint/node_modules/jshint-json/json.js:4 console.log(JSON.stringify({ ^

TypeError: Converting circular structure to JSON at Object.stringify (native) at module.exports.reporter (/home/egens/.atom/packages/linter-jshint/node_modules/jshint-json/json.js:4:20) at Object. (/home/egens/.atom/packages/linter-jshint/node_modules/jshint/src/cli.js:635:39) at Socket. (/home/egens/.atom/packages/linter-jshint/node_modules/jshint/node_modules/cli/cli.js:841:18) at emitNone (events.js:72:20) at Socket.emit (events.js:166:7) at endReadableNT (_stream_readable.js:893:12) at doNTCallback2 (node.js:441:9) at process._tickCallback (node.js:355:17)

Error: /home/egens/.atom/packages/linter-jshint/node_modules/jshint-json/json.js:4
		console.log(JSON.stringify({
		                 ^
TypeError: Converting circular structure to JSON
    at Object.stringify (native)
    at module.exports.reporter (/home/egens/.atom/packages/linter-jshint/node_modules/jshint-json/json.js:4:20)
    at Object.<anonymous> (/home/egens/.atom/packages/linter-jshint/node_modules/jshint/src/cli.js:635:39)
    at Socket.<anonymous> (/home/egens/.atom/packages/linter-jshint/node_modules/jshint/node_modules/cli/cli.js:841:18)
    at emitNone (events.js:72:20)
    at Socket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:893:12)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
    at parameters.exit (/home/egens/.atom/packages/linter-jshint/node_modules/atom-linter/lib/helpers.js:131:25)
    at triggerExitCallback (/usr/share/atom/resources/app.asar/src/buffered-process.js:213:47)
    at ChildProcess.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:235:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
Error: /home/egens/.atom/packages/linter-jshint/node_modules/jshint-json/json.js:4
		console.log(JSON.stringify({
		                 ^
TypeError: Converting circular structure to JSON
    at Object.stringify (native)
    at module.exports.reporter (/home/egens/.atom/packages/linter-jshint/node_modules/jshint-json/json.js:4:20)
    at Object.<anonymous> (/home/egens/.atom/packages/linter-jshint/node_modules/jshint/src/cli.js:635:39)
    at Socket.<anonymous> (/home/egens/.atom/packages/linter-jshint/node_modules/jshint/node_modules/cli/cli.js:841:18)
    at emitNone (events.js:72:20)
    at Socket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:893:12)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
    at parameters.exit (/home/egens/.atom/packages/linter-jshint/node_modules/atom-linter/lib/helpers.js:131:25)
    at triggerExitCallback (/usr/share/atom/resources/app.asar/src/buffered-process.js:213:47)
    at ChildProcess.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:235:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

**Comment by Arcanemagus** [comment]
Looks like this is an issue with `jshint-json`, you should file an issue [over there](https://github.com/sindresorhus/jshint-json) about this.
