### ISSUE TITLE
Failed to activate linter-jshint package

### ISSUE THREAD

**Issue by kuba-essentia** [AtomLinter/linter-jshint#227]
Seems similar to https://github.com/AtomLinter/linter-jshint/issues/169, but none of the suggested workarounds helped.

[Enter steps to reproduce below:]

1. Fire up Atom

**Atom Version**: 1.5.3
**System**: Mac OS X 10.10.5
**Thrown From**: [linter-jshint](https://github.com/AtomLinter/linter-jshint) package, v2.0.2

### Stack Trace

Failed to activate the linter-jshint package

```
At Cannot find module './helpers'

Error: Cannot find module './helpers'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/jakubkorzeniowski/.atom/packages/linter-jshint/node_modules/atom-package-deps/lib/index.js:32:16)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.activate (/Users/jakubkorzeniowski/.atom/packages/linter-jshint/lib/main.js:35:5)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:181:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:155:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:148:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:145:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:526:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:338:19
    at /Applications/Atom.app/Contents/Resources/app.asar/src/config.js:631:20
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Config.module.exports.Config.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:816:29)
    at Config.module.exports.Config.setRawValue (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:608:19)
    at Config.module.exports.Config.set (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:227:14)
    at Config.module.exports.Config.removeAtKeyPath (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:377:12)
    at Package.module.exports.Package.enable (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:77:26)
    at PackageManager.module.exports.PackageManager.enablePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:165:14)
    at HTMLButtonElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:314:27)
    at HTMLButtonElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "my-github-profile",
      "ide-haskell",
      "language-haskell",
      "autocomplete-haskell",
      "haskell-ghc-mod",
      "ide-haskell-cabal",
      "linter-csslint"
    ],
    "themes": [
      "atom-material-ui",
      "one-dark-syntax"
    ]
  },
  "linter-jshint": {
    "browser": true,
    "esnext": true,
    "predef": [
      "require",
      "module",
      "exports",
      "console",
      "_",
      "Backbone",
      "d3",
      "$",
      "define",
      "expect",
      "it",
      "describe",
      "Bro",
      "R"
    ],
    "undef": true,
    "unused": true
  }
}
```

### Installed Packages

```coffee
# User
atom-jade, v0.3.0
atom-material-ui, v1.2.0
atom-python-debugger, v0.3.4
atomic-chrome, v0.3.0
color-picker, v2.1.1
emmet, v2.4.1
file-icons, v1.6.15
json-schema, v0.1.15
language-gherkin, v1.0.3
linter, v1.11.3
linter-flake8, v1.12.0
linter-jscs, v3.4.8
linter-jshint, v2.0.2
linter-jsxhint, v0.1.2
linter-raml, v0.2.2
minimap, v4.19.0
minimap-find-and-replace, v4.4.0
minimap-git-diff, v4.1.8
minimap-linter, v1.1.1
node-debugger, v1.4.3
pigments, v0.24.1
raml, v0.2.0
react, v0.14.1
sync-settings, v0.6.0
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by steelbrain** [comment]
If I had to guess, this is an atom upgrade issue, does a restart fix this for you?

**Comment by kuba-essentia** [comment]
Sadly it doesn't.

**Comment by Arcanemagus** [comment]
You case is slightly different than those, for some reason it looks like Atom just failed to download one of the files somehow when it installed the package. Can you try reinstalling it?

**Comment by kuba-essentia** [comment]
That helped, apologies for not trying it out earlier. cheers!

**Comment by Arcanemagus** [comment]
No worries, glad it was a simple fix :wink:.
