### ISSUE TITLE
Cannot find module 'shell-path'

### ISSUE THREAD

**Issue by mister11** [AtomLinter/linter-jshint#236]
It happens every time linter is fired (onchange, onsave). Reinstall did not help. 

```
Error: Cannot find module 'shell-path'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at findOutPath (/Users/svenko11/.atom/packages/linter-jshint/node_modules/atom-linter/node_modules/consistent-path/lib/index.js:24:21)
    at getPath (/Users/svenko11/.atom/packages/linter-jshint/node_modules/atom-linter/node_modules/consistent-path/lib/index.js:17:16)
    at Object.exec (/Users/svenko11/.atom/packages/linter-jshint/node_modules/atom-linter/lib/helpers.js:106:59)
    at Object.execNode (/Users/svenko11/.atom/packages/linter-jshint/node_modules/atom-linter/lib/index.js:50:18)
    at Object.<anonymous> (/Users/svenko11/.atom/packages/linter-jshint/lib/main.js:111:38)
    at [object Generator].next (native)
    at step (/Users/svenko11/.atom/packages/linter-jshint/lib/main.js:3:273)
    at /Users/svenko11/.atom/packages/linter-jshint/lib/main.js:3:443
    at Object.lint (/Users/svenko11/.atom/packages/linter-jshint/lib/main.js:3:99)
    at promises.push.Promise.then._this.emitter.emit.linter (/Users/svenko11/.atom/packages/linter/lib/linter-registry.js:63:26)
    at /Users/svenko11/.atom/packages/linter/lib/linter-registry.js:62:23
    at Set.forEach (native)
    at LinterRegistry.lint (/Users/svenko11/.atom/packages/linter/lib/linter-registry.js:60:18)
    at /Users/svenko11/.atom/packages/linter/lib/linter.coffee:98:16
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /Users/svenko11/.atom/packages/linter/lib/editor-linter.js:30:20
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1067:27)
    at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1037:19)
    at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:630:26)
    at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:545:18)
    at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:528:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:649:35)
    at atom-workspace.commandRegistry.add.core:save (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:173:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:570:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:378:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

**Comment by steelbrain** [comment]
The simpler fix

1. Uninstall linter-jshint
1. Reinstall linter-jshint

The other simpler fix

```js
cd /Users/svenko11/.atom/packages/linter-jshint/
rm -rf node_modules/atom-linter
npm install atom-linter@latest
```

**Comment by Arcanemagus** [comment]
@steelbrain They said a reinstall didn't help, so let's at least hear back from them before closing :wink:.

**Comment by mister11** [comment]
Well, I'm not sure which fix actually worked because I've done both and problem was gone once I've restarted Atom.
