### ISSUE TITLE
JSHint return an invalid response, check your console for more info

### ISSUE THREAD

**Issue by ZStelmo** [AtomLinter/linter-jshint#259]
Start giving this error .
`       let parsed
        try {
          parsed = JSON.parse(result)
        } catch (_) {
          console.error('[Linter-JSHint]', _, result)
          atom.notifications.addWarning('[Linter-JSHint]',
            { detail: 'JSHint return an invalid response, check your console for more info' }
          )
          return results
        }
`

**Comment by jwerts** [comment]
Getting the same error popping up after updating to Atom 1.7.0.  I see this in the console:

```
[Linter-JSHint] SyntaxError: Unexpected end of input
    at Object.parse (native)
    at Object.<anonymous> (C:/Users/jwerts/.atom/packages/linter-jshint/lib/main.js:124:25)
    at [object Generator].next (native)
    at step (C:\Users\jwerts\.atom\packages\linter-jshint\lib\main.js:3:273)
    at process._tickCallback (node.js:392:9) (anonymous function) @ /C:/Users/jwerts/.atom/packages/linter-jshint/lib/main.js:123
```

**Comment by ZStelmo** [comment]
Duplicated
