### ISSUE TITLE
The package doesn't work anymore

### ISSUE THREAD

**Issue by XiaofengdiZhu** [AtomLinter/linter-jshint#273]
After I uninstalled it and installed again, it still doesn't work
A notification appears every time I edit the js files:
JsHint return an invalid response, check your console for more info.

**Comment by Arcanemagus** [comment]
What version of Atom are you using?
What OS are you on?
Do you get any additional information printed to the Developer Tools console?

**Comment by XiaofengdiZhu** [comment]
atom version：1.6.2
OS：Windows 10
Here is an error in console：
[Linter-JSHint] SyntaxError: Unexpected end of input
    at Object.parse (native)
    at Object.<anonymous> (C:/Users/admin/.atom/packages/linter-jshint/lib/main.js:124:25)
    at [object Generator].next (native)
    at step (C:\Users\admin\.atom\packages\linter-jshint\lib\main.js:3:273)
    at process._tickCallback (node.js:368:9) (anonymous function) @ /C:/Users/admin/.atom/packages/linter-jshint/lib/main.js:123

**Comment by Arcanemagus** [comment]
Your Atom version is out of date, after updating that can you place a breakpoint [here](https://github.com/AtomLinter/linter-jshint/blob/v2.1.0/lib/main.js#L123) in the Developer Tools, try to lint a file, and see what `result` contains?

**Comment by Arcanemagus** [comment]
Closing due to a lack of response, if you are still experiencing issues please re-open this!
