### ISSUE TITLE
jsdoc comments break linter

### ISSUE THREAD

**Issue by dylansteele8** [AtomLinter/linter-jshint#318]
When I started to add a jsdoc comment `/**`, the linter throws a bunch of errors.
```
Error: /Users/<user>/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:5309 throw err; ^

TypeError: Cannot read property 'id' of null at Object.x.nud (/Users/<user>/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:3228:26) at expression (/Users/<user>/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:884:34) at /Users/<user>/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:2427:23 at Object.x.led (/Users/<user>/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:1151:16) at expression (/Users/<user>/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:922:36) at Object.fud (/Users/<user>/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:4599:7) at expression (/Users/<user>/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:881:32) at statement (/Users/<user>/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:1632:9) at statements (/Users/<user>/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:1677:16) at itself (/Users/<user>/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:5288:9)
Error: /Users/<user>/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:5309
        throw err;
        ^
TypeError: Cannot read property 'id' of null
    at Object.x.nud (/Users/<user>/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:3228:26)
    at expression (/Users/<user>/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:884:34)
    at /Users/<user>/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:2427:23
    at Object.x.led (/Users/<user>/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:1151:16)
    at expression (/Users/<user>/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:922:36)
    at Object.fud (/Users/<user>/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:4599:7)
    at expression (/Users/<user>/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:881:32)
    at statement (/Users/<user>/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:1632:9)
    at statements (/Users/<user>/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:1677:16)
    at itself (/Users/<user>/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:5288:9)
    at ChildProcess.<anonymous> (/Users/<user>/.atom/packages/linter-jshint/node_modules/atom-linter/node_modules/sb-exec/lib/index.js:36:20)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:477:12)
```

**Comment by Arcanemagus** [comment]
From the stack trace this is a bug within `jshint` itself, does it work on the CLI if you save the file right when you start that?

**Comment by dylansteele8** [comment]
I haven't been able to reproduce this issue so I'm closing it. Sorry to bother.

**Comment by Arcanemagus** [comment]
No worries 😉

**Comment by bonanzakrak** [comment]
I was able to reproduce it. And know when it happens.

    module.exports = {
        method1: function(){
        },
        method2: function(){
        },
        method3: function(){
        }
    };


when you try to comment out ```method2``` using ```/*``` it throws an error (stack trace below). When you comment out with coma it is fine. but sometimes you don't want that.

```
Error: /Users/user/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:5386
        throw err;
        ^
TypeError: Cannot read property 'id' of null
    at Object.x.nud (/Users/user/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:3240:26)
    at expression (/Users/user/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:888:34)
    at /Users/user/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:1389:20
    at Object.x.led (/Users/user/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:1155:16)
    at expression (/Users/user/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:926:36)
    at statement (/Users/user/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:1636:9)
    at statements (/Users/user/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:1681:16)
    at itself (/Users/user/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:5365:9)
    at lint (/Users/user/.atom/packages/linter-jshint/node_modules/jshint/src/cli.js:495:8)
    at Object.<anonymous> (/Users/user/.atom/packages/linter-jshint/node_modules/jshint/src/cli.js:634:9)
    at ChildProcess.<anonymous> (/Users/user/.atom/packages/linter-jshint/node_modules/sb-exec/lib/index.js:56:20)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:477:12)
```
