### ISSUE TITLE
Fatal Error on Windows

### ISSUE THREAD

**Issue by AttilaSATAN** [AtomLinter/linter-jshint#320]
Hi everyone. There is a repeating error on my windows 10 setup.

```bash
Error: C:\Users\Attila.atom\packages\linter-jshint\node_modules\jshint\src\jshint.js:5328 throw err; ^

TypeError: Cannot read property 'type' of undefined at Object.nud (C:\Users\Attila.atom\packages\linter-jshint\node_modules\jshint\src\jshint.js:4461:23) at expression (C:\Users\Attila.atom\packages\linter-jshint\node_modules\jshint\src\jshint.js:898:34) at statement (C:\Users\Attila.atom\packages\linter-jshint\node_modules\jshint\src\jshint.js:1645:9) at statements (C:\Users\Attila.atom\packages\linter-jshint\node_modules\jshint\src\jshint.js:1691:16) at block (C:\Users\Attila.atom\packages\linter-jshint\node_modules\jshint\src\jshint.js:1806:13) at Object.fud (C:\Users\Attila.atom\packages\linter-jshint\node_modules\jshint\src\jshint.js:4274:11) at expression (C:\Users\Attila.atom\packages\linter-jshint\node_modules\jshint\src\jshint.js:895:32) at statement (C:\Users\Attila.atom\packages\linter-jshint\node_modules\jshint\src\jshint.js:1645:9) at statements (C:\Users\Attila.atom\packages\linter-jshint\node_modules\jshint\src\jshint.js:1691:16) at block (C:\Users\Attila.atom\packages\linter-jshint\node_modules\jshint\src\jshint.js:1806:13)
```

I don't think it is related but the first line which describes the file path is parsed wrongly `C:\Users\Attila.atom\packages\linter-jshint\node_modules\jshint\src\jshint.js:5328`  There should be a backslash `\` between .`..Attila` and `.atom` 

This is the error object:

```bash
Error: C:\Users\Attila\.atom\packages\linter-jshint\node_modules\jshint\src\jshint.js:5328
        throw err;
        ^

TypeError: Cannot read property 'type' of undefined
    at Object.nud (C:\Users\Attila\.atom\packages\linter-jshint\node_modules\jshint\src\jshint.js:4461:23)
    at expression (C:\Users\Attila\.atom\packages\linter-jshint\node_modules\jshint\src\jshint.js:898:34)
    at statement (C:\Users\Attila\.atom\packages\linter-jshint\node_modules\jshint\src\jshint.js:1645:9)
    at statements (C:\Users\Attila\.atom\packages\linter-jshint\node_modules\jshint\src\jshint.js:1691:16)
    at block (C:\Users\Attila\.atom\packages\linter-jshint\node_modules\jshint\src\jshint.js:1806:13)
    at Object.fud (C:\Users\Attila\.atom\packages\linter-jshint\node_modules\jshint\src\jshint.js:4274:11)
    at expression (C:\Users\Attila\.atom\packages\linter-jshint\node_modules\jshint\src\jshint.js:895:32)
    at statement (C:\Users\Attila\.atom\packages\linter-jshint\node_modules\jshint\src\jshint.js:1645:9)
    at statements (C:\Users\Attila\.atom\packages\linter-jshint\node_modules\jshint\src\jshint.js:1691:16)
    at block (C:\Users\Attila\.atom\packages\linter-jshint\node_modules\jshint\src\jshint.js:1806:13)
    at parameters.exit (C:\Users\Attila\.atom\packages\linter-jshint\node_modules\atom-linter\lib\helpers.js:47:27)
    at triggerExitCallback (C:\Users\Attila\AppData\Local\atom\app-1.9.6\resources\app.asar\src\buffered-process.js:215:47)
    at ChildProcess.<anonymous> (C:\Users\Attila\AppData\Local\atom\app-1.9.6\resources\app.asar\src\buffered-process.js:237:18)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
```

**Comment by AttilaSATAN** [comment]
Ok! I find the source of the problem.
It cannot lint `yield()` typo.
```javascript

    function* registerRoutes() {
      for (let route of config.routes) {
        let endPoint = new app.icEndPoints.EndPoint(route);
        yield().promise;

      }
    }
```

**Comment by Arcanemagus** [comment]
That error looks to be thrown from the `jshint` code itself, do you have the same issue if you run it from the CLI?

**Comment by AttilaSATAN** [comment]
Yes it jshint who throws. I tried it on jshint.com online editor which uses v2.9.2 and get the  `Uncaught TypeError: Cannot read property 'type' of undefined` error.

I'm openning a new issiue on jshint repo.

**Comment by AttilaSATAN** [comment]
it seams that they realized that too and found a solution  at their [#2978](https://github.com/jshint/jshint/pull/2978)
