### ISSUE TITLE
Errors while editing a Ruby file

### ISSUE THREAD

**Issue by gerrywastaken** [AtomLinter/linter-jshint#324]
If I'm editing a ruby file and midway (before saving) through my edit there is a syntax error, I get a big red error popup from linter-jshint. This pretty much means I have to disable this linter as otherwise it makes editing a file very painful. Any idea what might be causing this?

```
Error: /private/tmp/bleh.rb:1:1: error: unexpected token kELSIF /private/tmp/bleh.rb:1: elsif /private/tmp/bleh.rb:1: ^~~~~ /private/tmp/bleh.rb: Parser::SyntaxError: unexpected token kELSIF
Error: /private/tmp/bleh.rb:1:1: error: unexpected token kELSIF
/private/tmp/bleh.rb:1: elsif
/private/tmp/bleh.rb:1: ^~~~~
/private/tmp/bleh.rb: Parser::SyntaxError: unexpected token kELSIF
    at ChildProcess.<anonymous> (/Users/gerry/.atom/packages/linter-jshint/node_modules/atom-linter/node_modules/sb-exec/lib/index.js:36:20)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:477:12)
Close All
Error: /private/tmp/bleh.rb:1:1: error: unexpected token kELSIF /private/tmp/bleh.rb:1: elsif /private/tmp/bleh.rb:1: ^~~~~ /private/tmp/bleh.rb: Parser::SyntaxError: unexpected token kELSIF
Error: /private/tmp/bleh.rb:1:1: error: unexpected token kELSIF
/private/tmp/bleh.rb:1: elsif
/private/tmp/bleh.rb:1: ^~~~~
/private/tmp/bleh.rb: Parser::SyntaxError: unexpected token kELSIF
    at ChildProcess.<anonymous> (/Users/gerry/.atom/packages/linter-jshint/node_modules/atom-linter/node_modules/sb-exec/lib/index.js:36:20)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:477:12)

```

I was able to trigger the above errors by creating a ruby file containing a single `elsif` and nothing else. Then just hitting the arrow keys was enough to trigger these errors.

**Comment by gerrywastaken** [comment]
This appears to be a problem with linter-reek, as removing linter-jshint didn't actually fix the issue it just jumpted to linter-reek. However after disabling linter-reek the problem did not occur with linter-jshint.
