### ISSUE TITLE
Comment after coma breaks jshint

### ISSUE THREAD

**Issue by bonanzakrak** [AtomLinter/linter-jshint#352]
When adding comment block with ```/*``` or ```/**``` jshint throws an error. It happens only when i add that comment after a coma. Example code:

    module.exports = {
        method1: function(){
        },
        method2: function(){
        },
        method3: function(){
        }
    };

when you try to comment out ```method2``` using ```/*``` it throws an error (stack trace below). When you comment out with coma it is fine. but sometimes you don't want that.

```
Error: /Users/user/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:5386
        throw err;
        ^
TypeError: Cannot read property 'id' of null
    at Object.x.nud (/Users/user/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:3240:26)
    at expression (/Users/user/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:888:34)
    at /Users/user/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:1389:20
    at Object.x.led (/Users/user/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:1155:16)
    at expression (/Users/user/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:926:36)
    at statement (/Users/user/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:1636:9)
    at statements (/Users/user/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:1681:16)
    at itself (/Users/user/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:5365:9)
    at lint (/Users/user/.atom/packages/linter-jshint/node_modules/jshint/src/cli.js:495:8)
    at Object.<anonymous> (/Users/user/.atom/packages/linter-jshint/node_modules/jshint/src/cli.js:634:9)
    at ChildProcess.<anonymous> (/Users/user/.atom/packages/linter-jshint/node_modules/sb-exec/lib/index.js:56:20)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:477:12)
```

**Comment by Arcanemagus** [comment]
Again, just like with #318 this error is coming from JSHint itself, do you see it when you run `jshint` on the CLI?

**Comment by bonanzakrak** [comment]
Sadly yes.

```
/usr/local/lib/node_modules/jshint/src/jshint.js:5386
        throw err;
        ^

TypeError: Cannot read property 'id' of null
    at Object.x.nud (/usr/local/lib/node_modules/jshint/src/jshint.js:3240:26)
    at expression (/usr/local/lib/node_modules/jshint/src/jshint.js:888:34)
    at /usr/local/lib/node_modules/jshint/src/jshint.js:1389:20
    at Object.x.led (/usr/local/lib/node_modules/jshint/src/jshint.js:1155:16)
    at expression (/usr/local/lib/node_modules/jshint/src/jshint.js:926:36)
    at statement (/usr/local/lib/node_modules/jshint/src/jshint.js:1636:9)
    at statements (/usr/local/lib/node_modules/jshint/src/jshint.js:1681:16)
    at itself (/usr/local/lib/node_modules/jshint/src/jshint.js:5365:9)
    at lint (/usr/local/lib/node_modules/jshint/src/cli.js:495:8)

    at /usr/local/lib/node_modules/jshint/src/cli.js:656:7
```

**Comment by Arcanemagus** [comment]
Looks like this is https://github.com/jshint/jshint/issues/3004, please follow that issue for more details!
