### ISSUE TITLE
my default .jshintrc file always throw execption

### ISSUE THREAD

**Issue by simonchan2013** [AtomLinter/linter-jshint#361]
Hello, I try to set a `.jshintrc` file as my default config, but it alway throw the `SyntaxError: Unexpected token :` Error,

I had add the config to the `config.cson`

```
"linter-jshint":
    executablePath: "/Users/Ming/workspace/sysconf/atom-config/jshint/.jshintrc"
```

my `.jshintrc` file is:
```json
{
  "esversion": 6
}
```

and then any time I open a js file, it will alert these error message:
```
File 0Project 0No Issuesserver/handlers/asset/asset.wp.basic.js1:1
LFUTF-8JavaScriptfeature/ITS-2338_pre_calculate_for_adjustment
Error: /Users/Ming/workspace/sysconf/atom-config/jshint/.jshintrc:2 "esversion": 6 ^ SyntaxError: Unexpected token : at Object.exports.runInThisContext (vm.js:76:16) at Module._compile (module.js:528:28) at Object.Module._extensions..js (module.js:565:10) at Module.load (module.js:473:32) at tryModuleLoad (module.js:432:12) at Function.Module._load (module.js:424:3) at Module.runMain (module.js:590:10) at run (bootstrap_node.js:402:7) at startup (bootstrap_node.js:157:9) at bootstrap_node.js:521:3
Error: /Users/Ming/workspace/sysconf/atom-config/jshint/.jshintrc:2
  "esversion": 6
             ^
SyntaxError: Unexpected token :
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:528:28)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:402:7)
    at startup (bootstrap_node.js:157:9)
    at bootstrap_node.js:521:3
    at ChildProcess.<anonymous> (/Users/Ming/.atom/packages/linter-jshint/node_modules/sb-exec/lib/index.js:56:20)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
```

it this any wrong I made? wish your response

**Comment by Arcanemagus** [comment]
The `executablePath` setting, as stated in [the readme](https://github.com/AtomLinter/linter-jshint#settings), is supposed to be the path of `jshint` itself, _not_ your configuration file.

**Comment by simonchan2013** [comment]
I move the ` .jshintrc` file to the home path: `~`, and then it works well, thanks

**Comment by Arcanemagus** [comment]
Glad to hear it!
