### ISSUE TITLE
Error when adding docblock '/**'

### ISSUE THREAD

**Issue by MartialSeron** [AtomLinter/linter-jshint#363]
When I start to add a docblock with /**, it shows me an error : 

> Error:
>
> /home/martial/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:5438
>       throw err;
>        ^
>TypeError: Cannot read property 'id' of null
    at Object.x.nud (/home/martial/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:3250:26)
    at expression (/home/martial/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:888:34)
    at /home/martial/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:1385:20
    at Object.x.led (/home/martial/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:1155:16)
    at expression (/home/martial/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:926:36)
    at statement (/home/martial/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:1633:9)
    at statements (/home/martial/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:1678:16)
    at itself (/home/martial/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:5417:9)
    at lint (/home/martial/.atom/packages/linter-jshint/node_modules/jshint/src/cli.js:495:8)
    at Object.<anonymous> (/home/martial/.atom/packages/linter-jshint/node_modules/jshint/src/cli.js:634:9)
    at ChildProcess.<anonymous> (/home/martial/.atom/packages/linter-jshint/node_modules/sb-exec/lib/index.js:56:20)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:477:12)

Here's my code

```javascript
/* globals GlpiUsers: false */

"use strict";

const Bluebird = require('bluebird');
const squel = require('squel');

module.exports = {
  migrate       : 'safe',
  schema        : true,
  autoPK        : false,
  autoCreatedAt : false,
  autoUpdatedAt : false,
  tableName     : 'glpi_users',
  connection    : 'glpi',

  attributes : {
    id                             : {type: 'integer', primaryKey: true, unique: true, autoIncrement: true},
    name                           : {type: 'string'},
    password                       : {type: 'string'},
    phone                          : {type: 'string'},
    phone2                         : {type: 'string'},
    mobile                         : {type: 'string'},
    realname                       : {type: 'string'},
    firstname                      : {type: 'string'},
    locations_id                   : {type: 'integer', defaultsTo: '0'},
    language                       : {type: 'string'},
    use_mode                       : {type: 'integer', defaultsTo: '0'},
    list_limit                     : {type: 'integer'},
    is_active                      : {type: 'boolean', defaultsTo: true},
    comment                        : {type: 'text'},
    auths_id                       : {type: 'integer', defaultsTo: '0'},
    authtype                       : {type: 'integer', defaultsTo: '0'},
    last_login                     : {type: 'datetime'},
    date_mod                       : {type: 'datetime'},
    date_sync                      : {type: 'datetime'},
    is_deleted                     : {type: 'boolean', defaultsTo: false},
    profiles_id                    : {type: 'integer', defaultsTo: '0'},
    entities_id                    : {type: 'integer', defaultsTo: '0'},
    usertitles_id                  : {type: 'integer', defaultsTo: '0'},
    usercategories_id              : {type: 'integer', defaultsTo: '0'},
    date_format                    : {type: 'integer'},
    number_format                  : {type: 'integer'},
    names_format                   : {type: 'integer'},
    csv_delimiter                  : {type: 'string'},
    is_ids_visible                 : {type: 'boolean'},
    dropdown_chars_limit           : {type: 'integer'},
    use_flat_dropdowntree          : {type: 'boolean'},
    show_jobs_at_login             : {type: 'boolean'},
    priority_1                     : {type: 'string'},
    priority_2                     : {type: 'string'},
    priority_3                     : {type: 'string'},
    priority_4                     : {type: 'string'},
    priority_5                     : {type: 'string'},
    priority_6                     : {type: 'string'},
    followup_private               : {type: 'boolean'},
    task_private                   : {type: 'boolean'},
    default_requesttypes_id        : {type: 'integer'},
    password_forget_token          : {type: 'string'},
    password_forget_token_date     : {type: 'datetime'},
    user_dn                        : {type: 'text'},
    registration_number            : {type: 'string'},
    show_count_on_tabs             : {type: 'boolean'},
    refresh_ticket_list            : {type: 'integer'},
    set_default_tech               : {type: 'boolean'},
    personal_token                 : {type: 'string'},
    personal_token_date            : {type: 'datetime'},
    display_count_on_home          : {type: 'integer'},
    notification_to_myself         : {type: 'boolean'},
    duedateok_color                : {type: 'string'},
    duedatewarning_color           : {type: 'string'},
    duedatecritical_color          : {type: 'string'},
    duedatewarning_less            : {type: 'integer'},
    duedatecritical_less           : {type: 'integer'},
    duedatewarning_unit            : {type: 'string'},
    duedatecritical_unit           : {type: 'string'},
    display_options                : {type: 'text'},
    is_deleted_ldap                : {type: 'boolean', defaultsTo: false},
    pdffont                        : {type: 'string'},
    picture                        : {type: 'string'},
    begin_date                     : {type: 'datetime'},
    end_date                       : {type: 'datetime'},
    keep_devices_when_purging_item : {type: 'integer'},
    privatebookmarkorder           : {type: 'text'},
    backcreated                    : {type: 'boolean'},
    task_state                     : {type: 'integer'},

    emails: {collection: 'glpiuseremails', via: 'users_id'}
  },

  /** //---> bug here
  
  findByEmail: function(email, isAccount, callback){
    if ( typeof isAccount === 'function' ){
      callback = isAccount;
      isAccount = null;
    } else isAccount = isAccount || null;
    let select = squel.select();

    select.from('glpi_users', 'u')
    .left_join('glpi_useremails', 'ue', 'ue.users_id = u.id')
    .left_join('glpi_tickets_users', 'tu', 'tu.users_id = u.id')

    .where('u.is_deleted = 0')
    .where('ue.email like ?', email)

    .group('name')
    .group('phone')
    .group('realname')
    .group('firstname')
    .group('email')

    .order('nbtickets', false)
    .order('u.id', false)
    ;

    if (isAccount === true)
      select.where("u.name not like 'user%'");
    else if (isAccount === false)
      select.where("u.name like 'user%'");

    if (typeof callback === 'function') {
      return GlpiUsers.query(select.toString(), callback);
    }
    return Bluebird.promisify(GlpiUsers.query)(select.toString());
  }
};```

**Comment by Arcanemagus** [comment]
That bug is coming from `jshint`, please file it there as there is nothing we can do to fix it here.

**Comment by Arcanemagus** [comment]
Marking this as closed since this isn't a bug in this package.
