### ISSUE TITLE
Uncaught Error: Cannot find module 'atom-package-deps'

### ISSUE THREAD

**Issue by BadLame** [AtomLinter/linter-jshint#409]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Linux Mint
**Thrown From**: [linter-jshint](https://github.com/AtomLinter/linter-jshint) package 3.1.2

### Stack Trace

Uncaught Error: Cannot find module 'atom-package-deps'

```
At /home/andrei/atom-1.11.1/out/app/node_modules/tree-view/lib/file.coffee:1

Error: Cannot find module 'atom-package-deps'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/opt/atom/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/opt/atom/resources/app/src/module-cache.js:354:1)
    at Module.require (opt/atom/resources/app/static/index.js:40:43)
    at require (/opt/atom/resources/app/src/native-compile-cache.js:66:1)
    at installLinterJSHintDeps (/packages/linter-jshint/lib/main.js:39:9)
```

### Commands

```
     -4:22.3.0 settings-view:install-packages-and-themes (input.hidden-input)
     -3:20.4.0 core:confirm (input.hidden-input)
  2x -3:19.5.0 core:backspace (input.hidden-input)
     -3:19.1.0 editor:delete-to-beginning-of-word (input.hidden-input)
     -3:16.9.0 core:confirm (input.hidden-input)
     -2:33.2.0 editor:move-to-first-character-of-line (input.hidden-input)
     -2:31.3.0 core:confirm (input.hidden-input)
     -1:10.9.0 core:page-up (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:06.0 editor:move-to-first-character-of-line (input.hidden-input)
     -1:05.5.0 editor:delete-to-end-of-word (input.hidden-input)
     -1:04.7.0 core:delete (input.hidden-input)
     -1:04.0 editor:move-to-end-of-screen-line (input.hidden-input)
  2x -0:59.8.0 core:confirm (input.hidden-input)
  2x -0:23.8.0 core:move-up (input.hidden-input)
     -0:21.8.0 core:move-down (input.hidden-input)
     -0:20.8.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
apex-syntax 0.1.0 
apex-ui 0.2.1 
atom-clock 0.1.8 
busy-signal 1.4.3 
intentions 1.1.2 
linter 2.1.4 
linter-htmlhint 1.3.3 
linter-jshint 3.1.2 
linter-ui-default 1.6.0 
pure-syntax 0.2.1 
```

**Comment by Arcanemagus** [comment]
Please re-install the package, Atom sometimes fails to properly install all the dependencies.

**Comment by BadLame** [comment]
Damn it! I'd find the reason!
Dunno why, but jshint hates 'setTimeout' function.

**Comment by BadLame** [comment]
Sample:
https://goo.gl/photos/GdkSxruaTxPQn1Ch9
https://goo.gl/photos/aFXSkc7SnpiaU1CB9

**Comment by Arcanemagus** [comment]
@BadLame that's a separate issue from what you first reported, and has been reported as https://github.com/sindresorhus/jshint-json/issues/1. Unfortunately there's nothing we can do about that here.
