### ISSUE TITLE
Uncaught TypeError: Arguments to path.join must be strings

### ISSUE THREAD

**Issue by seleckis** [AtomLinter/linter-jshint#41]
I use Linter with Linter JSHint. Every time I start atom.io I get this error. Tried to reinstall atom, Linter and Linter JSHint — no luck.

**Atom Version**: 0.163.0
**System**: Mac OS X 10.10.1
**Thrown From**: [linter](https://github.com/AtomLinter/Linter) package, v0.9.0

### Stack Trace

Uncaught TypeError: Arguments to path.join must be strings

```
At path.js:384

TypeError: Arguments to path.join must be strings
  at Object.exports.join (path.js:384:15)
  at LinterJshint.Linter.getNodeExecutablePath (/Users/seleckis/.atom/packages/linter/lib/linter.coffee:104:10)
  at LinterJshint.Linter.getCmdAndArgs (/Users/seleckis/.atom/packages/linter/lib/linter.coffee:80:25)
  at LinterJshint.Linter.lintFile (/Users/seleckis/.atom/packages/linter/lib/linter.coffee:112:24)
  at /Users/seleckis/.atom/packages/linter/lib/linter-view.coffee:138:18
  at Array.forEach (native)
  at /Users/seleckis/.atom/packages/linter/lib/linter-view.coffee:137:18
  at Object.oncomplete (fs.js:93:15)

```

### Commands

```
```

### Config

```
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "deep-syntax"
    ],
    "disabledPackages": [
      "archive-view",
      "atom-jshint",
      "atom-lint",
      "autocomplete-plus",
      "autocomplete",
      "autocomplete-paths",
      "autocomplete-snippets",
      "autosave",
      "autoflow",
      "background-tips",
      "bookmarks",
      "color-picker",
      "deprecation-cop",
      "encoding-selector",
      "go-to-line",
      "language-c",
      "language-go",
      "language-java",
      "language-objective-c",
      "language-perl",
      "language-python",
      "language-ruby",
      "language-ruby-on-rails",
      "language-shellscript",
      "language-toml",
      "markdown-preview",
      "package-generator",
      "release-notes",
      "spell-check",
      "status-bar",
      "styleguide",
      "timecop",
      "welcome",
      "wrap-guide",
      "linter-jscs"
    ]
  },
  "linter": {
    "lintOnChange": false
  }
}
```

### Installed Packages

```coffee
# User
Atom-Syntax-highlighting-for-Sass, v0.5.0
Stylus, v0.4.0
build, v0.21.0
deep-syntax, v0.1.0
language-jade, v0.3.0
linter, v0.9.0
linter-jshint, v0.1.0
save-session, v0.11.1

# Dev

```

/cc @atom/core

**Comment by dmnd** [comment]
This is actually a problem in linter core. See atomlinter/linter#329. But it's fixed in the latest version; please upgrade!
