### ISSUE TITLE
TypeError: undefined is not a function   at new LinterJshint (/home/mrtemp/.atom/packages/linter-jshint/lib/linter-jshint.coffee:28:5)

### ISSUE THREAD

**Issue by miketamis** [AtomLinter/linter-jshint#45]
linter not working and getting this error in console.
```
/usr/share/atom/resources/app/src/package.js:230 Failed to activate package named 'linter' TypeError: undefined is not a function
  at LinterJshint.Linter (/home/mrtemp/.atom/packages/linter/lib/linter.coffee:54:33)
  at new LinterJshint (/home/mrtemp/.atom/packages/linter-jshint/lib/linter-jshint.coffee:28:5)
  at LinterView.initLinters (/home/mrtemp/.atom/packages/linter/lib/linter-view.coffee:51:27)
  at new LinterView (/home/mrtemp/.atom/packages/linter/lib/linter-view.coffee:33:6)
  at /home/mrtemp/.atom/packages/linter/lib/init.coffee:83:24
  at Workspace.module.exports.Workspace.observeTextEditors (/usr/share/atom/resources/app/src/workspace.js:268:9)
  at LinterInitializer.activate (/home/mrtemp/.atom/packages/linter/lib/init.coffee:80:39)
  at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app/src/package.js:225:27)
  at /usr/share/atom/resources/app/src/package.js:211:28
  at Package.module.exports.Package.measure (/usr/share/atom/resources/app/src/package.js:157:15)
  at Package.module.exports.Package.activate (/usr/share/atom/resources/app/src/package.js:205:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app/src/package-manager.js:410:21)
  at /usr/share/atom/resources/app/src/package-manager.js:397:33
  at Config.module.exports.Config.transact (/usr/share/atom/resources/app/src/config.js:342:16)
  at PackageManager.module.exports.PackageManager.activatePackages (/usr/share/atom/resources/app/src/package-manager.js:391:19)
  at PackageManager.module.exports.PackageManager.activate (/usr/share/atom/resources/app/src/package-manager.js:380:19)
  at Atom.module.exports.Atom.startEditorWindow (/usr/share/atom/resources/app/src/atom.js:605:21)
  at Object.<anonymous> (/usr/share/atom/resources/app/src/window-bootstrap.js:12:8)
  at Object.<anonymous> (/usr/share/atom/resources/app/src/window-bootstrap.js:23:4)
  at Module._compile (module.js:468:26)
  at Object.Module._extensions..js (module.js:486:10)
  at Module.load (/usr/share/atom/resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:318:12)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at window.onload (file:///usr/share/atom/resources/app/static/index.js:59:25)
```

**Comment by steelbrain** [comment]
Fixed after API migration
