### ISSUE TITLE
jshint requires an internet connection to run??

### ISSUE THREAD

**Issue by tustin2121** [AtomLinter/linter-jshint#509]
I lost network connectivity briefly while someone else was swapping out the router and as soon as my computer lost connection, jshint started throwing exceptions left and right every time I typed anything into atom (ie, every time it ran the linter). Once network connectivity was restored, the errors stopped. Windows 7, 64-bit.

````
net.js:10
const cares = process.binding('cares_wrap');
                      ^

Error: EFILE
    at net.js:10:23
    at net.js:1607:3
    at NativeModule.compile (bootstrap_node.js:528:7)
    at NativeModule.require (bootstrap_node.js:468:18)
    at internal/child_process.js:6:13
    at internal/child_process.js:889:3
    at NativeModule.compile (bootstrap_node.js:528:7)
    at NativeModule.require (bootstrap_node.js:468:18)
    at child_process.js:12:23
    at child_process.js:551:3

(anonymous) @ <embedded>:71616
C:\Users\Tim\.atom\packages\linter\lib\linter-registry.js:159 [Linter] Error running JSHint Error: net.js:10
const cares = process.binding('cares_wrap');
                      ^

Error: EFILE
    at net.js:10:23
    at net.js:1607:3
    at NativeModule.compile (bootstrap_node.js:528:7)
    at NativeModule.require (bootstrap_node.js:468:18)
    at internal/child_process.js:6:13
    at internal/child_process.js:889:3
    at NativeModule.compile (bootstrap_node.js:528:7)
    at NativeModule.require (bootstrap_node.js:468:18)
    at child_process.js:12:23
    at child_process.js:551:3

    at net.js:10:23
    at net.js:1607:3
    at NativeModule.compile (bootstrap_node.js:528:7)
    at NativeModule.require (bootstrap_node.js:468:18)
    at internal/child_process.js:6:13
    at internal/child_process.js:889:3
    at NativeModule.compile (bootstrap_node.js:528:7)
    at NativeModule.require (bootstrap_node.js:468:18)
    at child_process.js:12:23
    at child_process.js:551:3
    at ChildProcess.<anonymous> (C:\Users\Tim\.atom\packages\linter-eslint\node_modules\sb-exec\lib\index.js:56:20)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
````

Since when is a network connection required to run a linter program??

**Comment by Arcanemagus** [comment]
That's part of [Node.js itself](https://github.com/nodejs/node/blob/4760abcdd95070e06257b5408c2f72dcc787cfa9/lib/net.js#L10). I have _no_ idea why compiling the JSHint module is bringing that in though... in either case there is nothing that can be done about it here.

Do you see the same issue when running JSHint on the CLI?

**Comment by tustin2121** [comment]
I've never run JSHint from the command line, and I'm not sure how. Is there a way to do it with the installation in this linter plugin?
