### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by mogarick** [AtomLinter/linter-jshint#64]
[Enter steps to reproduce below:]

1. It just started to appear after update to version 0.194. It appears it triggers when switching to other tabs but it doesn't happens every time.

**Atom Version**: 0.194.0 :warning: **in 1.0 API Preview Mode** :warning:
**System**: Mac OS X 10.9.5
**Thrown From**: [linter-jshint](https://github.com/AtomLinter/linter-jshint) package, v0.1.2

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Users/rmontoya/.atom/packages/linter-jshint/lib/linter-jshint.coffee:52

TypeError: undefined is not a function
  at LinterJshint.destroy (/Users/rmontoya/.atom/packages/linter-jshint/lib/linter-jshint.coffee:52:17)
  at LinterView.remove (/Users/rmontoya/.atom/packages/linter/lib/linter-view.coffee:252:7)
  at /Users/rmontoya/.atom/packages/linter/lib/linter-view.coffee:124:8
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TextEditor.module.exports.TextEditor.destroyed (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:279:27)
  at TextEditor.module.exports.Model.destroy (/Applications/Atom.app/Contents/Resources/app.asar/src/model.js:45:58)
  at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:444:18)
  at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:179:22)
  at space-pen-ul.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4430:9)
  at space-pen-ul.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4116:28)

```

### Commands

```
     -8:02.4.0 editor:newline (atom-text-editor.editor)
     -8:01.9.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor)
     -8:01.9.0 editor:newline (atom-text-editor.editor)
  8x -7:55.5.0 core:backspace (atom-text-editor.editor)
     -7:50.1.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor)
     -7:50.1.0 editor:newline (atom-text-editor.editor)
     -7:49.8.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor)
     -7:49.8.0 editor:newline (atom-text-editor.editor)
     -7:44.4.0 core:move-up (atom-text-editor.editor)
  2x -7:27.5.0 core:move-right (atom-text-editor.editor)
  2x -7:19.8.0 core:move-down (atom-text-editor.editor)
     -7:18.8.0 snippets:next-tab-stop (atom-text-editor.editor)
     -7:18.8.0 snippets:expand (atom-text-editor.editor)
     -7:18.7.0 editor:indent (atom-text-editor.editor)
  2x -7:07.9.0 core:move-right (atom-text-editor.editor)
     -6:59.6.0 core:save (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".DS_Store",
      "app",
      "cache",
      "img"
    ],
    "disabledPackages": [
      "atom-jshint",
      "jshint",
      "js-refactor",
      "refactor"
    ],
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  },
  "linter-jshint": {
    "jshintExecutablePath": "/usr/local/bin/jshint"
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.24.1
block-comment, v0.4.1
emmet, v2.3.8
git-tab-status, v1.7.0
jsdoc, v0.9.0
linter, v0.12.1
linter-jshint, v0.1.2
project-manager, v1.15.5
save-session, v0.14.0
seti-syntax, v0.3.3
seti-ui, v0.6.3
turbo-javascript, v0.0.8

# Dev
No dev packages
```

**Comment by kurtschlatzer** [comment]
It's also happening with linter-scss-lint with the same behavior.

**Comment by mogarick** [comment]
It looks it's not related to switching tabs but closing them.
1. Open any JS file form your file tree
2. Close the tab
3. BANG! you get the "Uncaught TypeError: undefined is not a function" message.
