### ISSUE TITLE
getting this error some some reason alot

### ISSUE THREAD

**Issue by mattsta76** [AtomLinter/linter-jshint#688]
Any reason why i am getting this error and how to fix it??
C:\Users\matts_000\.atom\packages\linter\lib\linter-registry.js:155 [Linter] Error running JSHint Error: Process execution timed out
    at C:\Users\matts_000\.atom\packages\linter-jshint\node_modules\sb-exec\lib\index.js:89:18

![error js hint](https://user-images.githubusercontent.com/28722256/51446291-cbcdc380-1d5b-11e9-8eb4-7fe53eebc690.PNG)

**Comment by Arcanemagus** [comment]
You should only be getting that if `jshint` is taking longer than _10 seconds_ to run... how long does it take when you run it on the CLI?

**Comment by mattsta76** [comment]
I am trying to type in my code into atom text editor and get that error times 5 times in less then 10 seconds if that help you


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Landon Abney <notifications@github.com> Date: 21/1/19  9:13 am  (GMT+10:00) To: AtomLinter/linter-jshint <linter-jshint@noreply.github.com> Cc: mattsta76 <mattsta76@gmail.com>, Author <author@noreply.github.com> Subject: Re: [AtomLinter/linter-jshint] getting this error some some reason alot (#688) 
You should only be getting that if jshint is taking longer than 10 seconds to run... how long does it take when you run it on the CLI?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/AtomLinter/linter-jshint","title":"AtomLinter/linter-jshint","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/AtomLinter/linter-jshint"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Arcanemagus in #688: You should only be getting that if `jshint` is taking longer than _10 seconds_ to run... how long does it take when you run it on the CLI?"}],"action":{"name":"View Issue","url":"https://github.com/AtomLinter/linter-jshint/issues/688#issuecomment-455911806"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/AtomLinter/linter-jshint/issues/688#issuecomment-455911806",
"url": "https://github.com/AtomLinter/linter-jshint/issues/688#issuecomment-455911806",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by marcompte** [comment]
It is happening almost all the time now. Every time I write something, atom freezes for a few seconds and a bunch of timeout messages appear.

**Comment by potatofish** [comment]
I'm having the same issue - CLI is fast, but in atom I get timeout errors:

> [Linter] Error running JSHint Error: Process execution timed out
    at C:\Users\andre\.atom\packages\linter-jshint\node_modules\sb-exec\lib\index.js:89:18

I doesn't happen consistently, but it is frequent enough that I was able to immediately replicate it for capturing the above quote. 

Another interesting factor is that while I keep my settings synced both my laptop and desktop, and both use the same network drive'd jshint source, this is only occuring on my latptop.

Thoughts?

**Comment by Jerakin** [comment]
Installed linter-jshint with `Atom 1.45.0` the linter sometimes finds code errors, but eventutally (after switching/opening files) I get the reported error a _lot_ of times. Like a lot a lot. I do not think it takes 10 seconds before it shows in Atom, but the error gets spammed and freezes atom for a second or two.

**_Update (2 days after inital report):_**
I have not notice this as much after I restarted my computer.

**Comment by M457r0** [comment]
I too get this error at random, with ruby AND with php. Kind of annoying :(

The bigger the project, the _frequenter_
