### ISSUE TITLE
Uncaught Error: Cannot find module 'tmp'

### ISSUE THREAD

**Issue by inho820** [AtomLinter/linter-jshint#724]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.35.1 x64
**Electron**: 2.0.18
**OS**: Unknown Windows version
**Thrown From**: [linter-jshint](https://github.com/AtomLinter/linter-jshint) package 3.1.15

### Stack Trace

Uncaught Error: Cannot find module 'tmp'

```
At module.js:545

Error: Cannot find module 'tmp'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.35.1/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:154667)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:145974)
    at /packages/linter-jshint/node_modules/atom-linter/lib/helpers.js:23:12)
    at /packages/linter-jshint/node_modules/atom-linter/lib/helpers.js:139:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:146684)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:145974)
    at /packages/linter-jshint/node_modules/atom-linter/lib/index.js:139:16)
    at /packages/linter-jshint/node_modules/atom-linter/lib/index.js:329:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:146684)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:145974)
    at /packages/linter-stylelint/lib/helpers.js:4:37)
    at /packages/linter-stylelint/lib/helpers.js:294:2)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:146684)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:145974)
    at loadDeps (/packages/linter-stylelint/lib/index.js:14:15)
    at installLinterStylelintDeps (/packages/linter-stylelint/lib/index.js:33:7)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
atom-ternjs 0.19.1 
autoclose-html 0.23.0 
autocomplete 0.47.0 
autocomplete-modules 2.3.0 
autocomplete-project-paths 2.2.0 
busy-signal 2.0.1 
color-picker 2.3.0 
emmet 2.4.3 
gsap-snippets 0.5.0 
highlight-selected 0.16.0 
hyperclick 0.1.5 
intentions 1.1.5 
jQuery 1.2.6 
jquery-snippets 11.0.0 
language-babel 2.85.0 
linter 2.3.0 
linter-eslint 8.5.2 
linter-htmlhint 1.6.0 
linter-js-standard 6.1.1 
linter-jshint 3.1.15 
linter-stylelint 4.4.3 
linter-ui-default 1.7.1 
minimap 4.29.9 
minimap-hide 0.3.0 
pigments 0.40.2 
remote-ftp 2.2.2 
script 3.18.1 
swackets 0.35.0 
sync-settings 0.8.6 
```

**Comment by Arcanemagus** [comment]
Please try re-installing the package, occasionally a sub-dependency will fail to install properly.
